name: Utilizando Outputs no GitHub Actions
on:
  workflow_dispatch:

jobs:
  gerando_output:
    runs-on: ubuntu-latest
    steps:
      - name: Gerando número aleatório
        id: random_number
        run: |
          echo "Gerando número aleatório..."
          RANDOM_NUMBER=$((RANDOM % 100))
          echo "Número aleatório gerado: $RANDOM_NUMBER"
          echo "random_number=$RANDOM_NUMBER" >> $GITHUB_OUTPUT
      - name: Exibindo número aleatório
        run: |
          echo "Número aleatório gerado: ${{ steps.random_number.outputs.random_number }}"